[header]
msg = "Successfully loaded configurations."

[api]
token = "GRS0D5vK0ymAcBFsKt2KVwLoKott970G"

[websocket]
stock_ws = "wss://websockets.financialmodelingprep.com"
crypto_ws = "wss://crypto.financialmodelingprep.com"
forex_ws = "wss://forex.financialmodelingprep.com"
fwd_stock_ws = "0.0.0.0:8080"
fwd_forex_ws = ""
fwd_crypto_ws = ""
channel_bound = 100
shutdown_delay_ms = 60
batch_interval_ms = 500
buffer_size = 1000
